version: '3.4'

services:
  jupyterlab:
    image: sensorium
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    shm_size: 40g